ResolutionGraph {
    build_options: BuildConfig {
        dev_mode: true,
        generate_transaction_builders: false,
        generate_abis: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: Identifier(
                "Root",
            ),
            version: (
                0,
                0,
                0,
            ),
            authors: [],
            license: None,
        },
        addresses: None,
        dev_address_assignments: None,
        build: None,
        dependencies: {
            Identifier(
                "A",
            ): Dependency {
                local: "./deps_only/A",
                subst: Some(
                    {
                        Identifier(
                            "AA",
                        ): Assign(
                            00000000000000000000000000000001,
                        ),
                    },
                ),
                version: None,
                digest: None,
            },
            Identifier(
                "B",
            ): Dependency {
                local: "./deps_only/B",
                subst: Some(
                    {
                        Identifier(
                            "BA",
                        ): Assign(
                            00000000000000000000000000000001,
                        ),
                    },
                ),
                version: None,
                digest: None,
            },
        },
        dev_dependencies: {},
    },
    graph: Graph {
        Ty: "Directed",
        node_count: 4,
        edge_count: 4,
        edges: (1, 2), (0, 1), (3, 2), (0, 3),
        node weights: {
            0: Identifier(
                "Root",
            ),
            1: Identifier(
                "A",
            ),
            2: Identifier(
                "C",
            ),
            3: Identifier(
                "B",
            ),
        },
        edge weights: {
            0: Identifier(
                "C",
            ),
            1: Identifier(
                "A",
            ),
            2: Identifier(
                "C",
            ),
            3: Identifier(
                "B",
            ),
        },
    },
    package_table: {
        Identifier(
            "A",
        ): ResolutionPackage {
            resolution_graph_index: NodeIndex(1),
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "A",
                    ),
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {
                    Identifier(
                        "C",
                    ): Dependency {
                        local: "../C",
                        subst: Some(
                            {
                                Identifier(
                                    "AA",
                                ): RenameFrom(
                                    Identifier(
                                        "A",
                                    ),
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                    },
                },
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {
                Identifier(
                    "AA",
                ): (
                    Identifier(
                        "C",
                    ),
                    Identifier(
                        "A",
                    ),
                ),
            },
            resolution_table: {
                Identifier(
                    "AA",
                ): 00000000000000000000000000000001,
            },
        },
        Identifier(
            "B",
        ): ResolutionPackage {
            resolution_graph_index: NodeIndex(3),
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "B",
                    ),
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {
                    Identifier(
                        "C",
                    ): Dependency {
                        local: "../C",
                        subst: Some(
                            {
                                Identifier(
                                    "BA",
                                ): RenameFrom(
                                    Identifier(
                                        "A",
                                    ),
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                    },
                },
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {
                Identifier(
                    "BA",
                ): (
                    Identifier(
                        "C",
                    ),
                    Identifier(
                        "A",
                    ),
                ),
            },
            resolution_table: {
                Identifier(
                    "BA",
                ): 00000000000000000000000000000001,
            },
        },
        Identifier(
            "C",
        ): ResolutionPackage {
            resolution_graph_index: NodeIndex(2),
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "C",
                    ),
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        Identifier(
                            "A",
                        ): None,
                    },
                ),
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                Identifier(
                    "A",
                ): 00000000000000000000000000000001,
            },
        },
        Identifier(
            "Root",
        ): ResolutionPackage {
            resolution_graph_index: NodeIndex(0),
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "Root",
                    ),
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {
                    Identifier(
                        "A",
                    ): Dependency {
                        local: "./deps_only/A",
                        subst: Some(
                            {
                                Identifier(
                                    "AA",
                                ): Assign(
                                    00000000000000000000000000000001,
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                    },
                    Identifier(
                        "B",
                    ): Dependency {
                        local: "./deps_only/B",
                        subst: Some(
                            {
                                Identifier(
                                    "BA",
                                ): Assign(
                                    00000000000000000000000000000001,
                                ),
                            },
                        ),
                        version: None,
                        digest: None,
                    },
                },
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                Identifier(
                    "AA",
                ): 00000000000000000000000000000001,
                Identifier(
                    "BA",
                ): 00000000000000000000000000000001,
            },
        },
    },
}