ResolutionGraph {
    root_package: SourceManifest {
        package: PackageInfo {
            name: Identifier(
                "name",
            ),
            version: (
                0,
                1,
                2,
            ),
            authors: [],
            license: None,
        },
        addresses: None,
        dev_address_assignments: None,
        build: None,
        dependencies: {},
        dev_dependencies: {},
    },
    graph: Graph {
        Ty: "Directed",
        node_count: 1,
        edge_count: 0,
        node weights: {
            0: Identifier(
                "name",
            ),
        },
        edge weights: {},
    },
    memo_table: {
        Identifier(
            "name",
        ): ResolvedPackage {
            resolution_graph_index: NodeIndex(0),
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "name",
                    ),
                    version: (
                        0,
                        1,
                        2,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: None,
                dev_address_assignments: None,
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "/home/tzakian/libra/language/tools/move-build",
            renaming: {},
        },
    },
    resolution_table: {},
}